<br>

<center><img src='../Front_page/frontpage.png' style="width1:900px"></center>

<br>

<p style="font-size: 30px; text-align: center;"> <b>Session 3 - Text files, plots and multiplots. Widgets</b></p>

___

In [1]:
%who

Interactive namespace is empty.


# Live variables

The number of variables in this and the following notebooks will increase considerably. Remember to use `%who` and `type` to verify what variables are available (alive) and their respective type.

In [2]:
text = 'hola'

In [3]:
# Importing random, a Python Standard Library (PSL) or module. Numpy has a similar function.

import random 

In [4]:
# Two random numbers

a = random.randint(1, 10)
b = random.randint(1, 10)

print(a)
b

6


3

In [5]:
c = a + b

print(c)
type(c)

9


int

In [6]:
# Variables and modules available

%who

a	 b	 c	 random	 text	 


In [7]:
# Modules available

%who module

random	 


In [8]:
# Strings available

%who str

text	 


# Reading and writing files

In geosciences, we always have the necessity of reading and writing files that contain information that we want to process or deliver. Some common formats (from simpler to complex) to us are:

* Text (columnar data separated by space, commas...)
* LAS (just a pre-organized text file recognized by certain programs)
* Excel files (mainly arranged by columns)
* Image files (bmp, jpg, tiff,...)
* PDF (with text, images, and/or tables)
* SEGY

As is common in Python, there are different ways to input or output information, depending on the format of the files and the library or module you use. In this and the following session, we are going to explore simple ways to get information (text files and images) in and out of Python.

## Reading text files

Text files are the most straightforward files used in any computer (regardless of the operative system) to save information in a format familiar to us. Some specific uses of the text files are:

* Simple documents like notes, letters, emails, ...
* Data in columnar shape
* Keepers of parameters or environment variables for programs or operative systems
* Scripts or programs on different programming languages
* Communication between machines, programs, and persons
* Databases

Characters in text files were initially coded for electronic communication (teleprinters) based on different standards that in 1963 became the **ASCII** (American Standard Code for Information Interchange) code. Soon, it was clear that the ASCII code, which only had English characters, some mathematical,  and special symbols (128 characters), was insufficient for other written languages. So the ASCII code started to evolve into different codes until we got to the actual **UTF-8** (Universal Transformation Format) which has 1,112,064 characters, enough for all human written languages and disciplines. The UTF-8 standard is the base on which the World Wide Web works.

More information on character encoding at: https://www.w3schools.com/charsets/

The `zn.dat` file, in the Input folder, is a very simple text file with just one column that records "a series of 118 assays for Zn (weight % of zinc) made at two-meter intervals along a single sphalerite-quartz vein (see image below) in the **Pulacayo Mine** in Chile (Bolivia, in fact)." (Middleton, 2000). Zn is a tracer element for Au and Ag because it is a more mobile element and easier to analyze, so if Zn goes up, Au and Ag should also go up.

Data from: https://books.google.es/books/about/Data_Analysis_in_the_Earth_Sciences_Usin.html?id=mNsSAQAAIAAJ&redir_esc=y
<img src="NB_images\pulacayo_mine_bolivia.png" style="width:700px">

Pulacayo Mine south Bolivia. Source: https://www.mindat.org/loc-332.html

<img src="NB_images\vein_south_australia.png" style="width:700px">

Massive quartz vein outcropping in South Australia. Source:

https://www.reddit.com/r/geology/comments/cw3lpc/found_a_massive_quartz_vein_in_south_australia/

<img src="NB_images\vein_nalunaq_mine_australia.png" style="width:700px">

Quartz vein in a subterranean mine in South Australia. Source:

https://www.mining-technology.com/deals-analysis/fosterville-south-acquires-three-gold-projects-from-ecr-minerals/

### Reading single column text files

To load the zn.dat we are going to use the `genfromtxt()` command of the Numpy library which creates an array of float numbers.

References on the Numpy library at: https://numpy.org/

Later, in the coming sessions, we are going to load different text files using other commands or functions.

In [9]:
# Importing the Numpy library (agin, no problem)

import numpy as np

In [10]:
# Data loading and assignation. The Input folder is in the working directory

zn = np.genfromtxt('Input/zn.dat') # This is a relative path

# zn = np.genfromtxt('C:/Users/davidsoto/Documents/Python/NB/USB_AAPG_2/Session_3/Input/zn.dat') # An absolute path will work only in my pc

print(zn)

[17.7 17.8  9.5  5.2  4.1 19.2 12.4 15.8 20.8 24.1 14.7 21.6 12.8 11.9
 35.4 12.3 14.9 19.6 10.6 15.1 15.6  9.3  8.1 13.5 30.2 29.1  7.4 12.3
 13.6  9.5 13.1 27.4  8.8 11.4  6.4 11.  11.4 14.1 20.9 10.6 15.3 24.
 12.3  7.8  9.9 20.7 25.  19.1 13.1 27.4 15.2 12.2 10.1 12.3 16.7 18.6
  6.  10.6 11.3  4.7 10.9  6.   7.2  5.6  8.9  5.8  8.9  6.7  7.2  9.7
 10.8 17.9 10.9 13.7 22.3 10.2  5.1 13.9  9.  10.6 13.8  6.5  6.5 10.6
 10.6 23.  21.8 32.8 30.2 30.8 33.7 26.5 39.3 24.5 24.9 23.2 16.  20.9
 10.3 22.6 16.2 22.9 36.9 23.5 18.5 16.4 17.9 18.5 13.6  7.9 31.9 14.1
  7.1  3.9  3.7 22.5 27.6 17.3]


<div class="alert alert-block alert-warning">
<font size="6"> &#9757;&#127997;</font> <b>Question.</b> What kind of data is Zn if we used Numpy for its creation?
</div>

In [11]:
print(type(zn))

<class 'numpy.ndarray'>


You can use Unix commands inside your NB to check what is in your present working directory (pwd)

In [12]:
# Unix present working directory

%pwd

'C:\\Python\\NB\\USB_AAPG_2\\Session_3_Plots'

In [13]:
# Unix list

%ls

 Volume in drive C is OS
 Volume Serial Number is 0E88-496C

 Directory of C:\Python\NB\USB_AAPG_2\Session_3_Plots

09/15/2025  05:17 PM    <DIR>          .
11/02/2025  05:44 PM    <DIR>          ..
09/15/2025  05:17 PM    <DIR>          .ipynb_checkpoints
09/15/2025  05:17 PM    <DIR>          Input
09/15/2025  05:17 PM    <DIR>          NB_images
09/15/2025  05:17 PM    <DIR>          Output
04/11/2025  02:55 PM             8,113 session_3_exercises.ipynb
04/11/2025  04:04 PM            23,339 session_3_exercises_solutions.ipynb
04/11/2025  04:04 PM            54,766 session_3_text_plots_widgets.ipynb
               3 File(s)         86,218 bytes
               6 Dir(s)  262,889,779,200 bytes free


In [14]:
# Unix list

%ls Input

 Volume in drive C is OS
 Volume Serial Number is 0E88-496C

 Directory of C:\Python\NB\USB_AAPG_2\Session_3_Plots\Input

09/15/2025  05:17 PM    <DIR>          .
09/15/2025  05:17 PM    <DIR>          ..
03/24/2022  06:44 PM               597 rampi.csv
11/28/2022  10:05 AM           525,187 water_potability.csv
02/20/2025  05:20 PM               678 zn.dat
02/20/2025  05:20 PM               681 zn_w_info.dat
               4 File(s)        527,143 bytes
               2 Dir(s)  262,889,910,272 bytes free


Let's load a better-documented file, skiping the one-line header:

In [15]:
# Better-documented file

zn = np.genfromtxt('Input/zn_w_info.dat', skip_header = 2)

print(zn, '\n')
print(type(zn))

[17.7 17.8  9.5  5.2  4.1 19.2 12.4 15.8 20.8 24.1 14.7 21.6 12.8 11.9
 35.4 12.3 14.9 19.6 10.6 15.1 15.6  9.3  8.1 13.5 30.2 29.1  7.4 12.3
 13.6  9.5 13.1 27.4  8.8 11.4  6.4 11.  11.4 14.1 20.9 10.6 15.3 24.
 12.3  7.8  9.9 20.7 25.  19.1 13.1 27.4 15.2 12.2 10.1 12.3 16.7 18.6
  6.  10.6 11.3  4.7 10.9  6.   7.2  5.6  8.9  5.8  8.9  6.7  7.2  9.7
 10.8 17.9 10.9 13.7 22.3 10.2  5.1 13.9  9.  10.6 13.8  6.5  6.5 10.6
 10.6 23.  21.8 32.8 30.2 30.8 33.7 26.5 39.3 24.5 24.9 23.2 16.  20.9
 10.3 22.6 16.2 22.9 36.9 23.5 18.5 16.4 17.9 18.5 13.6  7.9 31.9 14.1
  7.1  3.9  3.7 22.5 27.6 17.3] 

<class 'numpy.ndarray'>


In [16]:
# Verif the type in the array and look for specific points

print(type(zn))
print(zn.dtype)    # n-bit-precision floating-point number, max range is 2**n
print(type(zn[0]),'\n')

print(zn[0])
print(zn[59])
print(zn[-1])

<class 'numpy.ndarray'>
float64
<class 'numpy.float64'> 

17.7
4.7
17.3


In [17]:
2**64

18446744073709551616

In [18]:
# Excessively large containers for single decimal numbers, it can be optimized
                            
print(np.finfo(np.float64))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



In [19]:
print(np.finfo(np.float16))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [20]:
# Some basic parameters of the zn array

print('samples =',len(zn))
print('min =', min(zn))
print('max =', max(zn))

zn_range = max(zn) - min(zn)

print('range =', zn_range)

samples = 118
min = 3.7
max = 39.3
range = 35.599999999999994


### Reading multi-column text files with missing values

To have a file with just a column is very rare. Normally we have files with several numerical columns, sometimes even columns with text. When you load a multi-column file an array is created with the corresponding number of columns, later each one can be defined as independent variables. Important, to operate with these variables, they have to have the same dimensions (same number of rows).

A common situation is to have several missing or lost values, places where the measurements were not possible. These missing values used to be indicated with special numbers such as -999.000, or -999.2500, or just with empty spaces. Numpy recognizes automatically empty spaces as missing values and replaces them with **nan**, not a number.

We are going to load the *rampi.csv* file, also in the Input folder, which is a five-column file that comes from a study of gold and associated elements (in ppm) in quartz veins in the **Rampi block prospect**, Indonesia (see image below from Google Earth):

<img src="NB_images\rampi_indonesia.png"  style="width:700px">

Data and information on the area in:

https://www.researchgate.net/publication/321018113_Occurrences_and_Characteristics_of_Gold_Mineralization_in_Rampi_Block_Prospect_North_Luwu_Regency_South_Sulawesi_Province_Indonesia/figures?lo=1

In [21]:
# Loading the multi-column file

rampi = np.genfromtxt('Input/rampi.csv', skip_header = 1, delimiter=',')

# The default data type of the np.genfromtxt command is float64 however you can set the loading to other types

print(rampi, '\n')
print(type(rampi))
rampi.shape

[[7.1000e-01 5.0000e-02 4.0700e+01 5.3080e+01 4.7890e+01]
 [7.1000e-01 6.0000e-02 1.0600e+01 5.1830e+01 3.6600e+01]
 [5.3000e-01 3.3000e-01 7.8680e+01 1.5790e+01 5.6360e+01]
 [8.0000e-02 1.2000e-01 6.8930e+01 1.4070e+01 4.4300e+01]
 [1.0000e-01 3.0000e-01 4.3110e+01 9.4890e+01 1.5070e+02]
 [4.0000e-02 1.0000e-01 1.1410e+01 3.8850e+01 5.0910e+01]
 [6.9000e-01 6.1200e+00 1.2220e+01 8.5590e+01 4.0190e+01]
 [1.7000e+01 6.0000e-02 6.3730e+01 6.1770e+01 3.5510e+01]
 [2.8200e+00 7.0000e-02 4.7650e+01 6.6310e+01 3.4080e+01]
 [7.1000e-01 6.0000e-02 9.3600e+00 3.3220e+01 4.0020e+01]
 [3.5700e+00 7.0000e-02 1.3610e+01 8.7060e+01 3.6630e+01]
 [7.0000e-01 6.0000e-02 3.7380e+01 5.3560e+01 4.6150e+01]
 [6.9000e-01 1.0000e-02 4.5960e+01 3.0760e+01 4.0020e+01]
 [7.0000e-01 2.1000e-01 3.9940e+01 2.2430e+01 3.4010e+01]
 [1.2000e-01 8.0000e-02 7.8680e+01 8.0090e+01 4.5880e+01]
 [7.0000e-01 1.0000e-02 1.4170e+01 4.6900e+01 3.9980e+01]
 [1.0000e-02 4.0000e-02 7.9070e+01 4.0280e+01 3.3840e+01]
 [1.0000e-02 1

(22, 5)

In [22]:
# 3rd column corresponding to Cu

rampi[:,2]

array([ 40.7 ,  10.6 ,  78.68,  68.93,  43.11,  11.41,  12.22,  63.73,
        47.65,   9.36,  13.61,  37.38,  45.96,  39.94,  78.68,  14.17,
        79.07,   7.93,   4.06, 127.73,    nan,    nan])

In [23]:
# Variables assignation

au = rampi[:,0]
ag = rampi[:,1]
cu = rampi[:,2]
zn2 = rampi[:,3]

# We use zn2 to avoid the overwriting of the zn from the Bolivian data

pb = rampi[:,4]

print('Silver:', '\n', ag, '\n')
print(type(ag))

Silver: 
 [0.05 0.06 0.33 0.12 0.3  0.1  6.12 0.06 0.07 0.06 0.07 0.06 0.01 0.21
 0.08 0.01 0.04 0.01 0.01 0.06  nan  nan] 

<class 'numpy.ndarray'>


In [24]:
# Some basic operations cannot be executed because some arrays have missing values (nan)

print('samples =',len(ag))
print('min =',np.min(ag))
print('max =',np.max(ag))

ag_range = np.max(ag) - np.min(ag)
print('range =', ag_range)

samples = 22
min = nan
max = nan
range = nan


In [25]:
# Arrays with nan require special functions that ignore the missing values

print('samples =',len(ag))

print('min =',np.nanmin(ag))
print('max =',np.nanmax(ag))

ag_range = np.nanmax(ag) - np.nanmin(ag)
print('range =', ag_range)

samples = 22
min = 0.01
max = 6.12
range = 6.11


In [26]:
# Not a number creation

x = np.nan
x

nan

In [ ]:
%who

<div class="alert alert-block alert-warning">
<font size="6"> &#127940;&#127997;</font> 
<b>Exercise 1 </b>

## Writing text files

It is common to write files to save simple texts and/or the value of a variable. In a pure Python way (no extra libraries used), let's start writing very simple text files, then another (report type) that incorporates the value of actual variables, and finally a columnar type similar to those we just loaded.

In [ ]:
from datetime import datetime

dt = datetime.now()
date = f'{dt.day}/{dt.month}/{dt.year}'
print(date)

In [ ]:
#  A very simple text file

dt = datetime.now()

# Open the file to write

file = open('Output/simple.txt', 'w')

# Write

file.write(f'Today is {date}\n')
file.write('\n')
file.write('This is a text file. \n')
file.write('\n')
file.write('In fact, a very simple one. \n')
file.write('\n')
file.write('This is the end.')

# Close the file

file.close()

# look at your pwd

Let's explore the file

In [ ]:
# Unix ls for linting

%ls

In [ ]:
# Unix ls for linting

%ls Output

In [ ]:
# Unix more to explore the txt

%more Output/simple.txt

In [ ]:
# Writing elements in a single-column text file by for loop

elementsRampi = open('Output/elements_rampi.txt', 'w')

for i in range(5):
    name = input('Enter the element symbol: ')
    elementsRampi.write(name + '\n')

elementsRampi.close()

In [ ]:
# Reading elements in a single-column text file and printing them

elementsRampi = open('Output/elements_rampi.txt', 'r')

for element in elementsRampi:
    print(element)

elementsRampi.close()

### Writing a simple text report

Let's write a simple text report that incorporates the value of actual variables calculated with the Bolivian data (*zn.dat*). For this purpose, we are going to use the `str()` function that converts the value of the variables into strings that can be included in the text file:

In [ ]:
# Text file with actual variables

file = open('Output/zn_basic_stat.txt','w')

file.write('Pulacayo nine, Bolivia. \n')
file.write('Statistical parameters. \n')
file.write('Weight % of Zinc in a quartz vein. \n')

file.write(' \n')
file.write('Minimum value = '+str(np.min(zn))+'\n')
file.write('Maximum value = '+str(np.max(zn))+' \n')
file.write('Range         = '+str(zn_range)+' \n')
file.write('Mean          = '+str(np.mean(zn))+' \n')
file.write(' \n')

file.close()

In [ ]:
# Unix more

%more Output/zn_basic_stat.txt

<div class="alert alert-block alert-warning">
<font size="6"> &#127940;&#127997;</font> 
<b>Exercise 2 </b>

### Writing single or multi-column text files

After manipulating your data you could have the necessity of exporting your results to other users or programs. The previous file is more suitable for single or few variables. For massive variables with a lot of rows, it is more convenient to export them in single or multi-column text files. Contrary to the previous examples, here it is important to take care of the format in which those variables are written. Maybe you need just four decimals or scientific notation. Here are two references about numbers and strings format:

https://pyformat.info/

https://mkaz.blog/code/python-string-format-cookbook/

In [ ]:
# For calculating ratios the columns have to have the same length

cuau_rat = cu/au
zn2au_rat = zn2/au
pbau_rat = pb/au
# znau_rat = zn/au

cuau_rat

In [ ]:
# Writing a ratio to a single-column file

np.savetxt('Output/cuau_rat.txt', cuau_rat, header='cuau ratio',fmt='%1.4f')

# fmt='%1.4f' write a float with this format: 20.2431

<div class="alert alert-block alert-warning">
<font size="6"> &#127940;&#127997;</font><b>Exercise 3 </b>
</div>

In [ ]:
len(rampi)

In [ ]:
# Writing all ratios to a multi-column text file

    # Creating the empty container (array) for the ratios

ratios = np.zeros((len(rampi), 3))
ratios

In [ ]:
# Filling the container with the ratios of the same dimension

ratios[:,0] = cuau_rat
ratios[:,1] = zn2au_rat
ratios[:,2] = pbau_rat
ratios

In [ ]:
# Saving the filled container to a multi-column text file

np.savetxt('Output/ratios.csv', ratios, delimiter=',', header='cuau,znau,pbau,', fmt='%1.2f')

# fmt='%1.2f' write a float with this format: 20.24

In [ ]:
# Unix more

%more Output/ratios.csv

<div class="alert alert-block alert-warning">
<font size="6"> &#127940;&#127997;</font><b>Exercise 4 </b>
</div>

### Matplotlib libraries

Matplotlib is a comprehensive external library for creating static, animated, and interactive visualizations of data in Python. Initially, the library sought to emulate the plots generated with Matlab, with the customization of the components of the plots (axis, grids, labels, etc.). From there Matplotlib played a pivotal role in promoting Python as a leading language in the field of data visualization and data science.

<br>
<img src="NB_images/matplotlib.jpg" style="width: 800px;"/>
<br>

As we saw in the Introduction, to install Matplotlib use the following command `pip install matplotlib` in a cmd window or `!pip install matplotlib`in the notebook. 

# Plots

We are graphical animals, for us is easier to make conclusions about a data set based on a bad graphic than on a sophisticated table. Python helps us with that as no other programming language. Let's see some basic plots such as:

* Simple point-line plot
* Scatter plot
* Histogram
* Bar and pie plots

**Matplotlib** is the library we are going to use for all plot-related issues. A huge variety of examples, with their respective code, can be seen at:

https://matplotlib.org/3.2.1/gallery/index.html

The references in the Matplotlib website are often complicated for a beginner, they are more suitable for computer scientists because they involve complex topics on programming like objects, sequences, attributes, ... Look at this example on sine and cosine plot and compare it with the one at the end of the previous session:

https://matplotlib.org/examples/pylab_examples/pythonic_matplotlib.html

Don't be afraid of picking whatever you need from these explanations and make your own version.

The methodology (paradigm) of coding presented on the Matplotlib website, is called **object-oriented programming**, and is powerful but more complicated. Here we are going to keep things simple and work with a simpler methodology called **procedural (state-based or state-oriented) programming** in which calculations or functions are executed one after the other.

## Single plots

By single plots, we mean a plot that are alone or isolated in a Jupyter cell output or inside a file.

### Point-line plots

For this demonstration, we are going to use the same data as the previous section, the data from Pulacayo Mine (*zn.dat*), and from the Rampi prospect block (*rampi.csv*). The `import` and loading commands are repeated in each section of the notebook so you can run each section individually.

In [ ]:
# Importing libraries

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Loading the Pulacayo data, single zinc concentration (weight %)

zn = np.genfromtxt('Input/zn.dat')
print('lenth of the zn file: ', len(zn))

In [ ]:
zn

In [ ]:
# A simple point-line plot of the original data. If x is not declared it assumes the position in the file.

plt.plot(zn)

plt.plot(zn, '.')

plt.show()

In [ ]:
# Let's plot the concentration of zinc against its real location along the vein, each 2 m

# This will be a plot with two real x-axis

x = range(0, 2*len(zn), 2)

plt.figure(figsize=(8, 5))

plt.plot(x, zn)

plt.xlabel("Distance (m)")
plt.ylabel("Weight %")
plt.title("Zn along quartz vein")
plt.show()

In [ ]:
# Let's show the mean value in the previous plot

y_mean = np.mean(zn) # y is a single value

plt.figure(figsize=(8,5))
plt.plot(x, zn)

# axhline draws a horizontal line based on y

plt.axhline(y_mean, ls="-", color='red', label="mean")

plt.legend()

plt.xlabel("Distance (m)")
plt.ylabel("Weight %")
plt.title("Zn along quartz vein")
plt.show()

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b> Exercise 5</b>
</div>

In [ ]:
# Let's fill between the mean and the curve

plt.figure(figsize=(8,5))
plt.plot(x, zn)
plt.axhline(y_mean, ls="-", color='black', label="mean")

plt.fill_between(x, zn, y_mean, where=(zn >= y_mean), facecolor='b', interpolate=True, label="over mean")
plt.fill_between(x, zn, y_mean, where=(zn <= y_mean), facecolor='r', interpolate=True, label="under mean")

plt.xlabel("Distance (m)")
plt.ylabel("Weight %")
plt.title("Zn along quartz vein")
plt.legend()
plt.show()

Let's work now with te Rampi data

In [ ]:
# Loading the Rampi data with five elements concentration (ppm), and variables assignation

rampi = np.genfromtxt('Input/rampi.csv', skip_header = 1, delimiter=',')

au = rampi[:,0]
ag = rampi[:,1]
cu = rampi[:,2]
zn2 = rampi[:,3]
pb = rampi[:,4]

In [ ]:
# Multi point-line plot of the Rampi data, just in the same file order, no x is involved, with grid.

plt.figure(figsize=(8,5))

plt.plot(au, 'y', label="Au")
plt.plot(ag, 'c', label="Ag")
plt.plot(cu, 'r', label="Cu")
plt.plot(zn2,'m', label="Zn")
plt.plot(pb, 'b', label="Pb")

plt.title("Rampi elements")
plt.xlabel("File order")
plt.ylabel("Concentration(ppm)")
plt.legend()
plt.grid(True)
plt.show()

Matplotlib colors: https://matplotlib.org/stable/gallery/color/named_colors.html

### Scatter plots

Scatter or cross plots are probably the most used plots in geosciences because they give you an idea about the relation of two variables.

In [ ]:
# Cross or scatter plot

plt.figure(figsize=(8,5))

plt.scatter(au,ag)

# plt.plot(au,ag,'o')

plt.title("Au vs. Ag")
plt.xlabel("Au (ppm)")
plt.ylabel("Ag (ppm)")
plt.grid(True)

# The limit of each axis can be controlled by

plt.xlim(0, 5)
plt.ylim(0, 0.5)

# The limit of both axles can be controlled by

plt.axis([0 , 5, 0, 0.5])

plt.show()

In [ ]:
# Cross plot in log scale

plt.figure(figsize=(8,5))

plt.loglog(au,ag, 'o')

# plt.semilogx(au,ag,'.')
# plt.semilogy(au,ag,'.')

# For just one axis used semilogx or semilogy

plt.title("Au vs. Ag")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Ag (ppm)")
plt.grid(True)
plt.show()

### Histograms

Histograms are important statistical plots, we are going to review them in detail in the next session, therefore here are only basic histograms:

In [ ]:
au

In [ ]:
# Single histogram

plt.figure(figsize=(8,5))

plt.hist(au)

au_mean = np.mean(au)
plt.axvline(au_mean, ls="-", color='red', label="mean")

plt.title("Au")
plt.xlabel("Concentration (ppm)")
plt.ylabel("Frequency")
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
# Double histogram with transparency (alpha)

plt.figure(figsize=(8,5))

# Au
plt.hist(au, label='Au')
plt.axvline(au_mean, ls="-", color='red', label="Au mean")

# Zn
zn_mean = np.nanmean(zn2)

plt.hist(zn2, alpha=0.5, label='Zn')

plt.axvline(zn_mean, ls="-", color='black', label="Zn mean")
plt.title("Au and Zn")
plt.xlabel("Concentration (ppm)")
plt.ylabel("Frequency")
plt.legend()
plt.grid(True)
plt.show()

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b>Exercise 6</b> 

### Bar and pie plots

Here you have two more types of plots, bar and pie plots. The categories (elements), data (sizes), and colors are the same in both cases. 

In [ ]:
# Bar plot

# Data to plot

elements = ['Au', 'Ag', 'Cu', 'Zn', 'Pb']
sizes = [np.nanmean(au), np.nanmean(ag), np.nanmean(cu), np.nanmean(zn2), np.nanmean(pb)]
x = range(len(elements))

# Plot properties
    
colors = ['y', 'c', 'r','m','b']

########################### Do not change the code below #####################################

# Plot & identifiers
    
plt.figure(figsize=(8,5))

plt.bar(x, sizes, align='center', color=colors, alpha=0.5)

plt.xticks(x, elements)

# Labels

plt.title('Rampi prospect')
plt.xlabel('Elements')
plt.ylabel('Average concentration (ppm)')
plt.show()

In [ ]:
# Pie plot

# New plot properties

explode = (0.2, 0.2, 0, 0, 0)

########################### Do not change the code below #####################################

# Plot & identifiers
    
plt.figure(figsize=(9,6))

plt.pie(sizes, explode=explode, labels=elements, colors=colors, wedgeprops={'alpha':0.5},

        autopct='%1.1f ppm', shadow=False, startangle=0)

plt.axis('equal')

# Labels
    
plt.title("Concentration of elements in the Rampi prospect")
plt.show()

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b>Exercise 7</b>

## Multiplots by subplot

With the Matploplib's **subplot** function it is possible to gather several plots in a composition, arranged based on a rectangular grid of raw and columns. The arguments (2,2,1) in the following command:

`plt.subplot(2,2,1)`
    
means the first plot in an arrange of two rows and two columns of plots, something like this:

<img src="NB_images\multiplot_example.png"  style="width:700px">

In [ ]:
# Building and saving a 2 x 3 multiplot with the Rampi data

plt.figure(figsize=(16,10))

plt.subplot(2,3,1)

# Point-line plot
plt.plot(au, 'y', label="Au")
plt.plot(ag, 'c', label="Ag")
plt.plot(cu, 'r', label="Cu")
plt.plot(zn2,'m', label="Zn")
plt.plot(pb, 'b', label="Pb")
plt.title("Elements")
plt.xlabel("File order")
plt.ylabel("ppm")
plt.legend()
plt.grid(True)

plt.subplot(2,3,2)

# Bar plot
elements = ('Au', 'Ag', 'Cu', 'Zn', 'Pb')
sizes = [np.nanmean(au), np.nanmean(ag), np.nanmean(cu), np.nanmean(zn2), np.nanmean(pb)]
x = np.arange(len(elements))   
colors = ['y', 'c', 'r','m','b']
plt.bar(x, sizes, align='center', alpha=0.5, color=colors)
plt.xticks(x, elements)
plt.title('Elements')
plt.ylabel('ppm')
plt.xlabel('Elements')
plt.grid(True)

plt.subplot(2,3,3)

# Cross plot
plt.loglog(au,ag,'o')
plt.title("Au vs. Ag")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Ag (ppm)")
plt.grid(True)

plt.subplot(2,3,4)

# Cross plot
plt.loglog(au,cu,'o')
plt.title("Au vs. Cu")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Cu (ppm)")
plt.ylim(1,200)
plt.grid(True)

plt.subplot(2,3,5)

# Cross plot
plt.loglog(au,zn2,'o')
plt.title("Au vs. Zn")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Zn (ppm)")
plt.ylim(1,200)
plt.grid(True)

plt.subplot(2,3,6)

# Cross plot
plt.loglog(au,pb,'o')
plt.title("Au vs. Pb")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Pb (ppm)")
plt.ylim(1,200)
plt.grid(True)

# Avoid the overlap between labels

plt.tight_layout()

# Saving multiplot to file

plt.savefig("Output/multiplot.png")
plt.savefig("Output/multiplot.pdf")

plt.show()

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b>Exercise 8</b>

## Multiplot by looping an array

Multiplots can be built by a loop, making the code shorter and more efficient. Let's see an example done by slicing the Rampi array: 

In [ ]:
rampi.shape

In [ ]:
# This in gold

rampi[:,0]

In [ ]:
%more Input/rampi.csv

In [ ]:
# Elements, colors, and position in the vein, according to the rampi array

elements = ['Au', 'Ag', 'Cu', 'Zn', 'Pb']
colors = ['y', 'c', 'r', 'm', 'b']
x = range(0, 3*rampi.shape[0], 3)

# Loop according to the number of columns in the rampi array

for i in range(rampi.shape[1]):
    
    plt.figure(figsize=(16,4))
    
    # Line plot of the element
    plt.subplot(1,2,1)
    plt.plot(x, rampi[:,i], color=colors[i], alpha=0.5)
    plt.xlim(0, 65)
    plt.xlabel('Position in the vein (m)')
    plt.ylabel('Concentration (ppm)')
    plt.title('Plot of '+elements[i])
    plt.grid()
    
    # Histogram of the element
    plt.subplot(1,2,2)
    plt.hist(rampi[:,i], color=colors[i], alpha=0.5)
    plt.ylabel('Frequency')
    plt.xlabel('Concentration (ppm)')
    plt.title('Histogram of '+elements[i])
    plt.grid()
    plt.savefig("Output/plot_"+elements[i]+".png")  
     
plt.tight_layout()
plt.show()        

## Multiplot by looping a list of lists

The list of lists allows us to save all the parameters related to each element in a single variable

In [ ]:
# list of list with element variable, color, and element name

elements = [[au, 'y', 'Au'], [ag, 'c', 'Ag'], [cu, 'r', 'Cu'], [zn2, 'm', 'Zn'], [pb, 'b', 'Pb']]

In [ ]:
# This in gold

elements[0]

In [ ]:
# Elements, colors, and position in the vein, according to the rampi array

elements = [[au, 'y', 'Au'], [ag, 'c', 'Ag'], [cu, 'r', 'Cu'], [zn2, 'm', 'Zn'], [pb, 'b', 'Pb']]

x = range(0, 3*rampi.shape[0], 3)

# Loop according to the number of columns in the rampi array

for element in elements:
    
    plt.figure(figsize=(16,4))
    
    # Line plot of the element
    plt.subplot(1,2,1)
    plt.plot(x, element[0], color=element[1], alpha=0.5)
    plt.xlim(0, 65)
    plt.xlabel('Position in the vein (m)')
    plt.ylabel('Concentration (ppm)')
    plt.title('Plot of '+element[2])
    plt.grid()
    
    # Histogram of the element
    plt.subplot(1,2,2)
    plt.hist(element[0], color=element[1], alpha=0.5)
    plt.ylabel('Frequency')
    plt.xlabel('Concentration (ppm)')
    plt.title(f'Histogram of {element[2]}')
    plt.grid()
    plt.savefig("Output/plot_"+element[2]+".png")  
     
plt.tight_layout()
plt.show()

## Multiplot by looping a list of dictionaries

The list of dictionaries allows us to save all the parameters related to each element in a single variable

In [ ]:
# Elements, 'color's, and position in the vein, according to the rampi array

elements = [{'element':au, 'color':'y', 'text':'Au'},
            {'element':ag, 'color':'c', 'text':'Ag'},
            {'element':cu, 'color':'r', 'text':'Cu'},
            {'element':zn2, 'color':'m', 'text':'Zn'},
            {'element':pb, 'color':'b', 'text':'Pb'}]

In [ ]:
# This in gold

elements[0]['element']

In [ ]:
x = range(0, 3*rampi.shape[0], 3)

# Loop according to the number of columns in the rampi array

for i in range(len(elements)):
    
    plt.figure(figsize=(16,4))
    
    # Line plot of the element
    plt.subplot(1,2,1)
    plt.plot(x, elements[i]['element'], color=elements[i]['color'], alpha=0.5)
    plt.xlim(0, 65)
    plt.xlabel('Position in the vein (m)')
    plt.ylabel('Concentration (ppm)')
    plt.title('Plot of '+elements[i]['text'])
    plt.grid()
    
    # Histogram of the element
    plt.subplot(1,2,2)
    plt.hist(elements[i]['element'], color=elements[i]['color'], alpha=0.5)
    plt.ylabel('Frequency')
    plt.xlabel('Concentration (ppm)')
    plt.title('Histogram of '+elements[i]['text'])
    plt.grid()
    plt.savefig('Output/plot_'+elements[i]['text']+'.png')

plt.close()    
plt.savefig('Output/plot_all_elements.png')    
plt.show()        

In summary, we have:

| Multiplot by | Number of plots | Number of effective lines of code |
| --- | --- |--- |
| Pure subplot | 6 | 53 |
| For loop | 10 | 19 |

<br>

The way forward is clear. Whenever possible, try to use for loops to build your multiplots, especially if you are repeating the same set of plots.

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b>Exercise 9</b>

# Interactive Notebook

There are other GUI (Graphic User Interface) tools that can bring even more power to the Jupyter Notebook. Let's see two of them, the Jupyter Notebook Widgets (a local set of tools) and a cross-platform GUI toolkit called Qt5.

## Widgets

Widgets are interactive controls or GUI tools that bring your Jupyter Notebook to life. There are many sources and types of widgets, however, all of them are focused on facilitating the interaction between the user and the notebook, minimizing the direct modification of the code. The main widgets are:

* Basic form controls like sliders, checkboxes, text inputs, and more
* Tabs, accordions, horizontal and vertical layout boxes, grid layouts
* Advanced controls like maps, 2d and 3d visualizations, data grids, and more

One of the main libraries of widgets is: https://ipywidgets.readthedocs.io/en/stable/

Let's see an example of widgets, an interactive slider, but first we need to install the necessary libraries:

In [ ]:
# !pip install ipywidgets

In [ ]:
# !pip install pyqt5

In [ ]:
# Importing libraries

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display
from matplotlib.widgets import Cursor

In [ ]:
# Sine plot with an interactive slider

# Plotting function

def plot_func(freq):
    plt.figure(figsize=(11,5))
    x = np.arange(0, 2*np.pi, 0.01) # 2*np.pi is 360º
    y = np.sin(x * freq)
    plt.plot(x, y)
    plt.xlabel('Radians')
    plt.ylabel('Amplitude')
    plt.grid()
    plt.show()

# The widget receives the plotting function

slider = widgets.FloatSlider(value=1, min=1, max=20, step=0.1, description="Frequency")
interact_plot = widgets.interactive(plot_func, freq=slider)

# Display the widget
display(interact_plot)

<div class="alert alert-block alert-warning">
<font size="6">&#127940;&#127997;</font><b>Exercise 10</b>

## Procedural vs. object-oriented programming

Before covering the last topic is worth seeing the difference between building a multiplot using the procedural and the object-oriented programming (OOP) paradigms. Here we are going to do the same scatter plot, with the same data, with both paradigms of coding:

In [ ]:
# Plot built with the procedural paradigm

plt.figure(figsize=(8,3))
plt.scatter(au, ag)    # The following three lines are equivalent to plt.loglog(au,ag,'.')

plt.yscale('log')
plt.xscale('log')

plt.title("Au vs. Ag")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Ag (ppm)")
plt.grid(True)
plt.show()

In [ ]:
# Plot built with the OOP paradigm

fig, ax = plt.subplots(figsize=(8, 3))
ax.scatter(au,ag)
ax.set_yscale('log')
ax.set_xscale('log')
ax.set_title("Au vs. Ag")
ax.set_xlabel("Log Au (ppm)")
ax.set_ylabel("Log Ag (ppm)")
ax.grid(True)

plt.show()

In code length both styles are equivalent. In the availability of examples and power, the **oop paradigm** (more modern) **is the winner** and is where we have to aim. To close the discussion on this important topic here is an animation that summarizes both paradigms applied to the same  multipole (remember that procedural, state-based, or state-oriented are the same paradigms):

<br>

<img src="NB_images\state_base_vs_object_oriented.gif"  style="width:700px">

The animation comes from this interesting article: 

https://towardsdatascience.com/plt-subplot-or-plt-subplots-understanding-state-based-vs-object-oriented-programming-in-pyplot-4ba0c7283f5d

## Qt5

A step up from the Jupyter Notebook widgets is Qt5, which is a cross-platform (Windows, Mac, Linux) UGI toolkit for application development (Spider for example). One of its many applications is that allows the plots to be independent from the notebook. More information on Qt5 at:

https://pypi.org/project/PyQt5/

Let's install and then activate Qt5:

In [ ]:
# Activation of Qt5 or inline plotting option (the default)

# %matplotlib qt
%matplotlib inline
# %matplotlib ipympl

In [ ]:
# Plot built with the procedural paradigm

# The num=1 between the brackets identifies the new plot window
# It is needed to avoid overwriting of the window

plt.figure(num=1, figsize=(8,5)) 
plt.scatter(au, ag)
plt.yscale('log')
plt.xscale('log')
plt.title("Au vs. Ag")
plt.xlabel("Log Au (ppm)")
plt.ylabel("Log Ag (ppm)")
plt.grid(True)
plt.show()

In [ ]:
# Plot built with the OOP paradigm and the cross-cursor

# The num=2 between the brackets identifies the new plot window
# It is needed to avoid overwriting of the window

fig, ax = plt.subplots(num=2, figsize=(11,5))
ax.scatter(au,ag)
ax.set_yscale('log')
ax.set_xscale('log')
ax.set_title("Au vs. Ag")
ax.set_xlabel("Log Au (ppm)")
ax.set_ylabel("Log Ag (ppm)")
ax.grid(True)

# The cross-cursor widget works only under the OOP paradigm and if the Qt5 is activated

cursor = Cursor(ax, horizOn=True, vertOn=True, linewidth=1.0, color='Red')

<div class="alert alert-block alert-warning">
<font size="6"> &#127881;</font>
<b>Congratulation!</b> We finished session 3, please work on the exercises.
</div>